// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEj_ssLjQcU7LRwC3we_4eHcDaY7Z4zAk',
    appId: '1:126531394945:web:8143d247009d8f782edc80',
    messagingSenderId: '126531394945',
    projectId: 'restorahub-2da2c',
    authDomain: 'restorahub-2da2c.firebaseapp.com',
    storageBucket: 'restorahub-2da2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhiso-lo4uQnhjLIvzqNOm71KefX7a3z4',
    appId: '1:126531394945:android:e40acb0de22fd94a2edc80',
    messagingSenderId: '126531394945',
    projectId: 'restorahub-2da2c',
    storageBucket: 'restorahub-2da2c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEj_ssLjQcU7LRwC3we_4eHcDaY7Z4zAk',
    appId: '1:126531394945:web:4e3223c8da4ad4292edc80',
    messagingSenderId: '126531394945',
    projectId: 'restorahub-2da2c',
    authDomain: 'restorahub-2da2c.firebaseapp.com',
    storageBucket: 'restorahub-2da2c.firebasestorage.app',
  );
}
